### ISSUE TITLE
Questions about the gamma point in the water's wannaier.win file

### ISSUE THREAD

**Issue by datieniuyyds** [CSIprinceton/workshop-july-2022#14]
Hi，@PabloPiaggi ，I  have read a few articles around 2000, which used a gamma point for the brillouin zone sampling of the bulk water system, so I set the KPOINTS file to 1 1 1 when I used vasp to do DFT calculations. The mp_grid in the .win file generated when doing Wannier90 calculation is 1 1 1. However, the mp_grid used in the wannier.win file you provided is 3 3 3. The file is the wannaier.win file for 11 water molecules.

1. Is there any requirement for the gamma point selection when calculating the wannier center of water?

2. In order to ensure the accuracy of the Wannier Center in the output file Wannier.wout, are there any other things that need to be paid attention to besides the parameters in Wannier.win you provided?

Looking forward to your answer, thank you very much.

**Comment by PabloPiaggi** [comment]
Hi @datieniuyyds, perhaps @salinelake can answer this question better because he wrote that part of the tutorial.

@salinelake, can you please answer this?

**Comment by salinelake** [comment]
1. The MP grid used for K-sampling is decided by the system you want to calculate. If you are not sure about which MD grid to use, you could check first the convergence of the Wannier center location with different densities of K points, say 1X1X1, 2X2X2, 3X3X3 grids.
2. Please read the user guide of wannier90 in case you need to adjust other parameters. In the tutorial, we only specify a minimal set of parameters. Other parameters to be paid attention to will vary case by case. I do not have a general answer.

**Comment by datieniuyyds** [comment]
Thanks for your answer, salinelake. Thank you PabloPiaggi.

**Comment by PabloPiaggi** [comment]
Glad we could help. I am closing the issue. Feel free to reopen it if you have other questions. You can also use the Discussions feature of GitHub.
